# Use container-based Travis with caching

languague: c
sudo: false

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - texinfo
    - qpdf
    - default-jdk
    - default-jre
    
cache:
  directories:
    - ~/Rlib     # R libraries
    - ~/texlive  # LaTex 
    - ~/bin      # pandoc 

# install dependencies
install:
  # Save R packages in Rlib
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > .Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
  - mkdir -p ~/.R
  - grep '\-g'  /etc/R/Makeconf | sed 's/-g//g' > ~/.R/Makevars # Turn off debug symbols
  # Build LaTex and pandoc
  - mkdir -p ~/bin
  - wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-texlive | bash
  - wget -q -O - https://github.com/yihui/crandalf/raw/master/inst/scripts/install-pandoc | bash
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH  
  # Install R packages
  - Rscript -e 'if (!require("devtools")) install.packages("devtools")'  
  - Rscript -e "if (!require('drat')) install.packages('drat')"
  - echo 'drat::addRepo("OHDSI")' >> .Rprofile  
  - Rscript -e "if (!require('rJava')) install.packages('rJava')"
  - Rscript -e "if (!require('aws.signature')) install.packages('aws.signature')"
  - Rscript -e "if (!require('httr')) install.packages('httr')"
  - Rscript -e "if (!require('XML')) install.packages('XML')"
  - Rscript -e "if (!require('OhdsiRTools')) install.packages('OhdsiRTools')"  
  
#before_script:
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
  
 # Build and check package
script:
  - R CMD build .
  - _R_CHECK_CRAN_INCOMING_=FALSE R CMD check "${PKG_TARBALL}" --as-cran
  - cat ${PKG_NAME}.Rcheck/00install.out # Print out install / compile log 

after_success:
  # Rebuild docker container
  - curl --data "build=true" -X POST https://registry.hub.docker.com/u/ohdsi/development/trigger/e51f720d-c4e7-45df-b042-5d8a362bd7e0/
  # Rebuild drat repo   
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
  
notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change
    
env:
  global:
    - secure: MEEblXFIzHLAO8T8FopnutpZKM3zMzGwweRBEGziGjoJwLe4sDaieBAn3F0K+EN4fS9tIw2reCulYbsEw+LvkluhYEKfZTiIhcrrPYp79xhXuV8vOymfqI8Lwoy6zIqt0fXhXx8KHSZPg4+wJ6/NY6MWRFsjxZAPSS3ECBt4naQ=
