# @file OhdsiSharing.R
#
# Copyright 2014 Observational Health Data Sciences and Informatics
#
# This file is part of OhdsiSharing
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# @author Observational Health Data Sciences and Informatics
# @author Martijn Schuemie

#' @title share
#'
#' @description
#' \code{share} copies the results to a central site. By default, it is sent to the OHDSI coordinating center.
#'
#' @details
#' Copies the results to a central site. By default, it is sent to the OHDSI coordinating center.
#' 
#' @param results	an results object generated by one of the OHDSI tools
#' @param ...		further arguments
#' 
#'  @examples \dontrun{
#'   connectionDetails <- createConnectionDetails(dbms="sql server", server="RNDUSRDHIT07.jnj.com")
#'   oscarResults <- oscar(connectionDetails, "cdm4_sim", "scratch", "TestDB")
#'   share(oscarResults)
#' }
#' @export
share <- function(results, ...){
	UseMethod("share") 
}

share.oscarResults <- function(oscarResults, ...) {
	conn <- connect(oscarResults$resultsConnectionDetails)
	tables <- c("OSCAR_analysis","OSCAR_results","OSCAR_statistic")
	randomPrefix <- round(runif(n=1,0,100000000))
	for (table in tables){
		writeLines(paste("Copying table",table,"to server"))
		filename = paste(table,"RData",sep=".")
		data <- dbReadTable(conn, table)
		save(data,file=filename)
		ftpUpload(filename, paste("ftp://ohdsi:omop2014@195.8.209.203/upload/",paste(randomPrefix,filename,sep="_")))
	}
	writeLines("Done")
}
